background {
    monitor =
    path = /home/udon/Dotfiles/hypr/walls/wall2.jpg
    blur_passes = 3
    blur_size    = 7
    brightness   = 0.5
}

input-field {
    monitor =
    size             = 300, 50
    outline_thickness = 2
    dots_size        = 0.25
    dots_spacing     = 0.2
    dots_center      = true
    outer_color      = rgb(F2CDCD)
    inner_color      = rgb(161320)
    font_color       = rgb(D9E0EE)
    fade_on_empty    = true
    placeholder_text = <i>Password...</i>
    hide_input       = false
    check_color      = rgb(ABE9B3)
    fail_color       = rgb(F28FAD)
    fail_text        = <i>Wrong password</i>
    position         = 0, -80
    halign           = center
    valign           = center
}

label {
    monitor     =
    text        = cmd[update:1000] date +"%H:%M"
    color       = rgba(D9E0EEff)
    font_size   = 72
    font_family = JetBrainsMono Nerd Font Bold
    position    = 0, 100
    halign      = center
    valign      = center
}

label {
    monitor     =
    text        = cmd[update:1000] date +"%A, %d %B %Y"
    color       = rgba(C9CBFFff)
    font_size   = 20
    font_family = JetBrainsMono Nerd Font
    position    = 0, 20
    halign      = center
    valign      = center
}
